name: ExaGOOP-CI

on:
  workflow_dispatch:
  push:
    branches: [ClangTidy]
  pull_request:
    branches: [ClangTidy]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - name: Check formatting
      uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: './Source'
        exclude: '.'
        extensions: 'H,h,cpp'
        clangFormatVersion: 20
  Lint-codespell:
    needs: Formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Dependencies
        run: |
          # Install Python packages
          python -m pip install --upgrade pip
          pip install codespell
      - name: Run codespell
        run: codespell --skip=".git,build"
