name: ExaGOOP-Docs

on:
  workflow_dispatch:
  push:
    branches: [ClangTidy]
    paths:
       - 'docs/**'
       - '.github/workflows/docs.yml'
  pull_request:
    branches: [ClangTidy]
    paths:
       - 'docs/**'
       - '.github/workflows/docs.yml'

jobs:
  Docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Dependencies
        run: |
          #Currently ignoring doxygen
          #export DEBIAN_FRONTEND=noninteractive
          #sudo apt-get update
          #sudo apt-get install -y --no-install-recommends doxygen graphviz
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install sphinxcontrib-bibtex
      - name: Configure
        run: cmake -B${{runner.workspace}}/build-docs ${{github.workspace}}/docs
      - name: Build
        working-directory: ${{runner.workspace}}/build-docs
        run:  |
           echo "::add-matcher::.github/problem-matchers/sphinx.json"
           cmake --build ${{runner.workspace}}/build-docs 2>&1 | tee -a build-output.txt
           touch ${{runner.workspace}}/build-docs/html/manual/html/.nojekyll
      - name: Report
        working-directory: ${{runner.workspace}}/build-docs
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          egrep "WARNING:|Warning:|warning:|ERROR:|Error:|error:" build-output.txt | sort | uniq | \
            awk 'BEGIN{i=0}{print $0}{i++}END{print "Warnings: "i}' > build-output-warnings.txt
          cat build-output-warnings.txt
          exit $(tail -n 1 build-output-warnings.txt | awk '{print $2}')
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/ClangTidy'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ${{runner.workspace}}/build-docs/html
          single-commit: true
